In [2]:
import pandas as pd

In [3]:
import pandas as pd

data = [10, 20, 30, 40]
s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [5]:
print(s["a"])

10

In [6]:
data = {"A": 50, "B": 60, "C": 70}
s = pd.Series(data)

print(s)

A    50
B    60
C    70
dtype: int64

In [2]:
import pandas as pd

data = {
    "Name": ["Riya", "Aman", "Priya"],
    "Age": [21, 22, 20]
}

df = pd.DataFrame(data)
print(df)

    Name  Age
0   Riya   21
1   Aman   22
2  Priya   20

In [3]:
df = pd.read_csv("people-1000.csv")
df

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer
...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer
996,997,ECddaFEDdEc4FAB,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator
997,998,2adde51d8B8979E,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor
998,999,Fb2FE369D1E171A,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person
999,1000,8b756f6231DDC6e,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability"

In [11]:
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer

In [12]:
df.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer
996,997,ECddaFEDdEc4FAB,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator
997,998,2adde51d8B8979E,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor
998,999,Fb2FE369D1E171A,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person
999,1000,8b756f6231DDC6e,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability"

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          1000 non-null   int64
 1   User Id        1000 non-null   object
 2   First Name     1000 non-null   object
 3   Last Name      1000 non-null   object
 4   Sex            1000 non-null   object
 5   Email          1000 non-null   object
 6   Phone          1000 non-null   object
 7   Date of birth  1000 non-null   object
 8   Job Title      1000 non-null   object
dtypes: int64(1), object(8)
memory usage: 70.4+ KB

In [14]:
df.describe()

             Index
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [16]:
df["First Name"]

0        Shelia
1            Jo
2        Sheryl
3       Whitney
4       Lindsey
         ...
995        Kurt
996       Donna
997       Cathy
998    Jermaine
999         Lee
Name: First Name, Length: 1000, dtype: object

In [4]:
f=pd.read_csv("Match_Info.csv")
df=pd.DataFrame(f)
df

,match_number,team1,team2,match_date,toss_winner,toss_decision,result,eliminator,winner,player_of_match,venue,city,team1_players,team2_players
0,336036,Rajasthan Royals,Mumbai Indians,2008-05-26,Rajasthan Royals,field,Win,NaN,Rajasthan Royals,Sohail Tanvir,Sawai Mansingh Stadium,Jaipur,"Kamran Akmal, SA Asnodkar, YK Pathan, SR Watso...","ST Jayasuriya, SR Tendulkar, AM Nayar, RV Utha..."
1,335995,Kings XI Punjab,Delhi Daredevils,2008-04-27,Delhi Daredevils,bat,Win,NaN,Kings XI Punjab,SM Katich,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, SM Katich, KC Sangakkara, DPMD Jayawar...","G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, M..."
2,1254108,Royal Challengers Bangalore,Mumbai Indians,2021-09-26,Mumbai Indians,field,Win,NaN,Royal Challengers Bangalore,GJ Maxwell,Dubai International Cricket Stadium,Dubai,"V Kohli, D Padikkal, KS Bharat, GJ Maxwell, AB...","RG Sharma, Q de Kock, Ishan Kishan, SA Yadav, ..."
3,829761,Kolkata Knight Riders,Delhi Daredevils,2015-05-07,Kolkata Knight Riders,bat,Win,NaN,Kolkata Knight Riders,PP Chawla,Eden Gardens,Kolkata,"RV Uthappa, G Gambhir, MK Pandey, PP Chawla, Y...","MK Tiwary, SS Iyer, JP Duminy, KM Jadhav, Yuvr..."
4,1216521,Chennai Super Kings,Mumbai Indians,2020-10-23,Mumbai Indians,field,Win,NaN,Mumbai Indians,TA Boult,Sharjah Cricket Stadium,NaN,"RD Gaikwad, F du Plessis, AT Rayudu, N Jagadee...","Q de Kock, Ishan Kishan, SA Yadav, SS Tiwary, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,336017,Kolkata Knight Riders,Delhi Daredevils,2008-05-13,Kolkata Knight Riders,bat,Win,NaN,Kolkata Knight Riders,Shoaib Akhtar,Eden Gardens,Kolkata,"Salman Butt, A Chopra, SC Ganguly, DJ Hussey, ...","G Gambhir, V Sehwag, AB de Villiers, MK Tiwary..."
1165,981007,Gujarat Lions,Mumbai Indians,2016-05-21,Gujarat Lions,field,Win,NaN,Gujarat Lions,SK Raina,Green Park,Kanpur,"AJ Finch, BB McCullum, SK Raina, KD Karthik, D...","RG Sharma, MJ Guptill, N Rana, KH Pandya, JC B..."
1166,980931,Rising Pune Supergiants,Royal Challengers Bangalore,2016-04-22,Rising Pune Supergiants,field,Win,NaN,Royal Challengers Bangalore,AB de Villiers,Maharashtra Cricket Association Stadium,Pune,"AM Rahane, F du Plessis, KP Pietersen, SPD Smi...","V Kohli, KL Rahul, AB de Villiers, SR Watson, ..."
1167,1304095,Royal Challengers Bangalore,Chennai Super Kings,2022-05-04,Chennai Super Kings,field,Win,NaN,Royal Challengers Bangalore,HV Patel,"Maharashtra Cricket Association Stadium, Pune",Pune,"V Kohli, F du Plessis, GJ Maxwell, MK Lomror, ...","RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ..."
1168,1136568,Kings XI Punjab,Royal Challengers Bangalore,2018-04-13,Royal Challengers Bangalore,field,Win,NaN,Royal Challengers Bangalore,UT Yadav,M.Chinnaswamy Stadium,Bengaluru,"KL Rahul, MA Agarwal, AJ Finch, Yuvraj Singh, ...","Q de Kock, BB McCullum, V Kohli, AB de Villier..."

In [5]:
df.shape

(1169, 14)

In [6]:
df.shape[0]

1169

In [7]:
df.size

16366

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_number     1169 non-null   int64
 1   team1            1169 non-null   object
 2   team2            1169 non-null   object
 3   match_date       1169 non-null   object
 4   toss_winner      1169 non-null   object
 5   toss_decision    1169 non-null   object
 6   result           1169 non-null   object
 7   eliminator       15 non-null     object
 8   winner           1146 non-null   object
 9   player_of_match  1169 non-null   object
 10  venue            1169 non-null   object
 11  city             1118 non-null   object
 12  team1_players    1169 non-null   object
 13  team2_players    1169 non-null   object
dtypes: int64(1), object(13)
memory usage: 128.0+ KB

In [5]:
df.columns

Index(['match_number', 'team1', 'team2', 'match_date', 'toss_winner',
       'toss_decision', 'result', 'eliminator', 'winner', 'player_of_match',
       'venue', 'city', 'team1_players', 'team2_players'],
      dtype='object')

In [9]:
df.ndim

2

In [11]:
df.dtypes

match_number        int64
team1              object
team2              object
match_date         object
toss_winner        object
toss_decision      object
result             object
eliminator         object
winner             object
player_of_match    object
venue              object
city               object
team1_players      object
team2_players      object
dtype: object

In [12]:
df.size

16366

In [13]:
df.columns

Index(['match_number', 'team1', 'team2', 'match_date', 'toss_winner',
       'toss_decision', 'result', 'eliminator', 'winner', 'player_of_match',
       'venue', 'city', 'team1_players', 'team2_players'],
      dtype='object')

In [14]:
df["winner"]

0                  Rajasthan Royals
1                   Kings XI Punjab
2       Royal Challengers Bangalore
3             Kolkata Knight Riders
4                    Mumbai Indians
                   ...
1164          Kolkata Knight Riders
1165                  Gujarat Lions
1166    Royal Challengers Bangalore
1167    Royal Challengers Bangalore
1168    Royal Challengers Bangalore
Name: winner, Length: 1169, dtype: object

In [15]:
df[["winner","player_of_match"]]

                           winner player_of_match
0                Rajasthan Royals   Sohail Tanvir
1                 Kings XI Punjab       SM Katich
2     Royal Challengers Bangalore      GJ Maxwell
3           Kolkata Knight Riders       PP Chawla
4                  Mumbai Indians        TA Boult
...                           ...             ...
1164        Kolkata Knight Riders   Shoaib Akhtar
1165                Gujarat Lions        SK Raina
1166  Royal Challengers Bangalore  AB de Villiers
1167  Royal Challengers Bangalore        HV Patel
1168  Royal Challengers Bangalore        UT Yadav

[1169 rows x 2 columns]

In [16]:
df.iloc[0]

match_number                                                  336036
team1                                               Rajasthan Royals
team2                                                 Mumbai Indians
match_date                                                2008-05-26
toss_winner                                         Rajasthan Royals
toss_decision                                                  field
result                                                           Win
eliminator                                                       NaN
winner                                              Rajasthan Royals
player_of_match                                        Sohail Tanvir
venue                                         Sawai Mansingh Stadium
city                                                          Jaipur
team1_players      Kamran Akmal, SA Asnodkar, YK Pathan, SR Watso...
team2_players      ST Jayasuriya, SR Tendulkar, AM Nayar, RV Utha...
Name: 0, dtype: object

In [17]:
df.iloc[0:5]

,match_number,team1,team2,match_date,toss_winner,toss_decision,result,eliminator,winner,player_of_match,venue,city,team1_players,team2_players
0,336036,Rajasthan Royals,Mumbai Indians,2008-05-26,Rajasthan Royals,field,Win,NaN,Rajasthan Royals,Sohail Tanvir,Sawai Mansingh Stadium,Jaipur,"Kamran Akmal, SA Asnodkar, YK Pathan, SR Watso...","ST Jayasuriya, SR Tendulkar, AM Nayar, RV Utha..."
1,335995,Kings XI Punjab,Delhi Daredevils,2008-04-27,Delhi Daredevils,bat,Win,NaN,Kings XI Punjab,SM Katich,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, SM Katich, KC Sangakkara, DPMD Jayawar...","G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, M..."
2,1254108,Royal Challengers Bangalore,Mumbai Indians,2021-09-26,Mumbai Indians,field,Win,NaN,Royal Challengers Bangalore,GJ Maxwell,Dubai International Cricket Stadium,Dubai,"V Kohli, D Padikkal, KS Bharat, GJ Maxwell, AB...","RG Sharma, Q de Kock, Ishan Kishan, SA Yadav, ..."
3,829761,Kolkata Knight Riders,Delhi Daredevils,2015-05-07,Kolkata Knight Riders,bat,Win,NaN,Kolkata Knight Riders,PP Chawla,Eden Gardens,Kolkata,"RV Uthappa, G Gambhir, MK Pandey, PP Chawla, Y...","MK Tiwary, SS Iyer, JP Duminy, KM Jadhav, Yuvr..."
4,1216521,Chennai Super Kings,Mumbai Indians,2020-10-23,Mumbai Indians,field,Win,NaN,Mumbai Indians,TA Boult,Sharjah Cricket Stadium,NaN,"RD Gaikwad, F du Plessis, AT Rayudu, N Jagadee...","Q de Kock, Ishan Kishan, SA Yadav, SS Tiwary, ..."

In [18]:
df.iloc[0:5,0:5]

,match_number,team1,team2,match_date,toss_winner
0,336036,Rajasthan Royals,Mumbai Indians,2008-05-26,Rajasthan Royals
1,335995,Kings XI Punjab,Delhi Daredevils,2008-04-27,Delhi Daredevils
2,1254108,Royal Challengers Bangalore,Mumbai Indians,2021-09-26,Mumbai Indians
3,829761,Kolkata Knight Riders,Delhi Daredevils,2015-05-07,Kolkata Knight Riders
4,1216521,Chennai Super Kings,Mumbai Indians,2020-10-23,Mumbai Indians

In [20]:
df.loc[0:3,"match_number":"result"]

,match_number,team1,team2,match_date,toss_winner,toss_decision,result
0,336036,Rajasthan Royals,Mumbai Indians,2008-05-26,Rajasthan Royals,field,Win
1,335995,Kings XI Punjab,Delhi Daredevils,2008-04-27,Delhi Daredevils,bat,Win
2,1254108,Royal Challengers Bangalore,Mumbai Indians,2021-09-26,Mumbai Indians,field,Win
3,829761,Kolkata Knight Riders,Delhi Daredevils,2015-05-07,Kolkata Knight Riders,bat,Win

In [21]:
df[df["city"]=="Ahmedabad"][["team1","team2"]]

                            team1                        team2
44                   Punjab Kings               Delhi Capitals
72               Rajasthan Royals               Mumbai Indians
96                 Gujarat Titans             Rajasthan Royals
118                Gujarat Titans          Chennai Super Kings
139                Gujarat Titans               Mumbai Indians
149                Gujarat Titans               Mumbai Indians
164                Gujarat Titans         Lucknow Super Giants
173              Rajasthan Royals          Sunrisers Hyderabad
215                Gujarat Titans                 Punjab Kings
272              Rajasthan Royals               Gujarat Titans
323              Rajasthan Royals        Kolkata Knight Riders
334              Rajasthan Royals              Deccan Chargers
338                Delhi Capitals               Gujarat Titans
383           Sunrisers Hyderabad               Gujarat Titans
392                Gujarat Titans               Mumbai Indians
411              Rajasthan Royals          Chennai Super Kings
426              Rajasthan Royals               Mumbai Indians
432              Rajasthan Royals              Kings XI Punjab
434   Royal Challengers Bangalore             Rajasthan Royals
454           Sunrisers Hyderabad        Kolkata Knight Riders
457           Chennai Super Kings               Gujarat Titans
467                Gujarat Titans               Mumbai Indians
482              Rajasthan Royals        Kolkata Knight Riders
549                  Punjab Kings  Royal Challengers Bangalore
568                Mumbai Indians                 Punjab Kings
569                Gujarat Titans  Royal Challengers Bengaluru
597   Royal Challengers Bangalore               Delhi Capitals
690              Rajasthan Royals             Delhi Daredevils
748              Rajasthan Royals          Chennai Super Kings
808                Gujarat Titans             Rajasthan Royals
810              Rajasthan Royals             Delhi Daredevils
823                  Punjab Kings               Gujarat Titans
865                Gujarat Titans          Sunrisers Hyderabad
892              Rajasthan Royals  Royal Challengers Bangalore
900                Gujarat Titans          Sunrisers Hyderabad
914   Royal Challengers Bengaluru                 Punjab Kings
927                Delhi Capitals               Gujarat Titans
944          Lucknow Super Giants               Gujarat Titans
949   Royal Challengers Bengaluru             Rajasthan Royals
1061               Gujarat Titans               Delhi Capitals
1083                 Punjab Kings        Kolkata Knight Riders
1114        Kolkata Knight Riders               Delhi Capitals
1133               Gujarat Titans        Kolkata Knight Riders
1150               Gujarat Titans          Chennai Super Kings
1158          Chennai Super Kings               Gujarat Titans

In [23]:
df[(df["toss_winner"]=="Rajasthan Royals") & (df["toss_decision"]=="bat")].shape[0]

44

In [24]:
# Create column
df["D1"]=0

In [25]:
df

,match_number,team1,team2,match_date,toss_winner,toss_decision,result,eliminator,winner,player_of_match,venue,city,team1_players,team2_players,D1
0,336036,Rajasthan Royals,Mumbai Indians,2008-05-26,Rajasthan Royals,field,Win,NaN,Rajasthan Royals,Sohail Tanvir,Sawai Mansingh Stadium,Jaipur,"Kamran Akmal, SA Asnodkar, YK Pathan, SR Watso...","ST Jayasuriya, SR Tendulkar, AM Nayar, RV Utha...",0
1,335995,Kings XI Punjab,Delhi Daredevils,2008-04-27,Delhi Daredevils,bat,Win,NaN,Kings XI Punjab,SM Katich,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, SM Katich, KC Sangakkara, DPMD Jayawar...","G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, M...",0
2,1254108,Royal Challengers Bangalore,Mumbai Indians,2021-09-26,Mumbai Indians,field,Win,NaN,Royal Challengers Bangalore,GJ Maxwell,Dubai International Cricket Stadium,Dubai,"V Kohli, D Padikkal, KS Bharat, GJ Maxwell, AB...","RG Sharma, Q de Kock, Ishan Kishan, SA Yadav, ...",0
3,829761,Kolkata Knight Riders,Delhi Daredevils,2015-05-07,Kolkata Knight Riders,bat,Win,NaN,Kolkata Knight Riders,PP Chawla,Eden Gardens,Kolkata,"RV Uthappa, G Gambhir, MK Pandey, PP Chawla, Y...","MK Tiwary, SS Iyer, JP Duminy, KM Jadhav, Yuvr...",0
4,1216521,Chennai Super Kings,Mumbai Indians,2020-10-23,Mumbai Indians,field,Win,NaN,Mumbai Indians,TA Boult,Sharjah Cricket Stadium,NaN,"RD Gaikwad, F du Plessis, AT Rayudu, N Jagadee...","Q de Kock, Ishan Kishan, SA Yadav, SS Tiwary, ...",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,336017,Kolkata Knight Riders,Delhi Daredevils,2008-05-13,Kolkata Knight Riders,bat,Win,NaN,Kolkata Knight Riders,Shoaib Akhtar,Eden Gardens,Kolkata,"Salman Butt, A Chopra, SC Ganguly, DJ Hussey, ...","G Gambhir, V Sehwag, AB de Villiers, MK Tiwary...",0
1165,981007,Gujarat Lions,Mumbai Indians,2016-05-21,Gujarat Lions,field,Win,NaN,Gujarat Lions,SK Raina,Green Park,Kanpur,"AJ Finch, BB McCullum, SK Raina, KD Karthik, D...","RG Sharma, MJ Guptill, N Rana, KH Pandya, JC B...",0
1166,980931,Rising Pune Supergiants,Royal Challengers Bangalore,2016-04-22,Rising Pune Supergiants,field,Win,NaN,Royal Challengers Bangalore,AB de Villiers,Maharashtra Cricket Association Stadium,Pune,"AM Rahane, F du Plessis, KP Pietersen, SPD Smi...","V Kohli, KL Rahul, AB de Villiers, SR Watson, ...",0
1167,1304095,Royal Challengers Bangalore,Chennai Super Kings,2022-05-04,Chennai Super Kings,field,Win,NaN,Royal Challengers Bangalore,HV Patel,"Maharashtra Cricket Association Stadium, Pune",Pune,"V Kohli, F du Plessis, GJ Maxwell, MK Lomror, ...","RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...",0
1168,1136568,Kings XI Punjab,Royal Challengers Bangalore,2018-04-13,Royal Challengers Bangalore,field,Win,NaN,Royal Challengers Bangalore,UT Yadav,M.Chinnaswamy Stadium,Bengaluru,"KL Rahul, MA Agarwal, AJ Finch, Yuvraj Singh, ...","Q de Kock, BB McCullum, V Kohli, AB de Villier...",0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_number     1169 non-null   int64
 1   team1            1169 non-null   object
 2   team2            1169 non-null   object
 3   match_date       1169 non-null   object
 4   toss_winner      1169 non-null   object
 5   toss_decision    1169 non-null   object
 6   result           1169 non-null   object
 7   eliminator       15 non-null     object
 8   winner           1146 non-null   object
 9   player_of_match  1169 non-null   object
 10  venue            1169 non-null   object
 11  city             1118 non-null   object
 12  team1_players    1169 non-null   object
 13  team2_players    1169 non-null   object
 14  D1               1169 non-null   int64
dtypes: int64(2), object(13)
memory usage: 137.1+ KB

In [27]:
df.isnull().sum()

match_number          0
team1                 0
team2                 0
match_date            0
toss_winner           0
toss_decision         0
result                0
eliminator         1154
winner               23
player_of_match       0
venue                 0
city                 51
team1_players         0
team2_players         0
D1                    0
dtype: int64

In [28]:
import numpy as np
data={"dhruv":[100,200,0,np.nan],"dhoni":[100,np.nan,0,np.nan],
      "kohli":[np.nan,90,78,12],"a":[200,100,200,300]}

df=pd.DataFrame(data)
df

   dhruv  dhoni  kohli    a
0  100.0  100.0    NaN  200
1  200.0    NaN   90.0  100
2    0.0    0.0   78.0  200
3    NaN    NaN   12.0  300

In [29]:
df.dropna(thresh=3, axis = 1)

   dhruv  kohli    a
0  100.0    NaN  200
1  200.0   90.0  100
2    0.0   78.0  200
3    NaN   12.0  300

In [30]:
df.dropna(subset=["dhoni"])

   dhruv  dhoni  kohli    a
0  100.0  100.0    NaN  200
2    0.0    0.0   78.0  200

In [31]:
df

   dhruv  dhoni  kohli    a
0  100.0  100.0    NaN  200
1  200.0    NaN   90.0  100
2    0.0    0.0   78.0  200
3    NaN    NaN   12.0  300

In [32]:
df.dropna(subset=["dhoni"])

   dhruv  dhoni  kohli    a
0  100.0  100.0    NaN  200
2    0.0    0.0   78.0  200

In [33]:
df["dhoni"].fillna("dhoni")

0    100.0
1    dhoni
2      0.0
3    dhoni
Name: dhoni, dtype: object

In [35]:
df.fillna(100,inplace=True)
df

   dhruv  dhoni  kohli    a
0  100.0  100.0  100.0  200
1  200.0  100.0   90.0  100
2    0.0    0.0   78.0  200
3  100.0  100.0   12.0  300

In [36]:
df["dhoni"].sum()

np.float64(300.0)

In [37]:
df["dhoni"].mean()

np.float64(75.0)

In [38]:
df.drop([0,1],axis=0)

   dhruv  dhoni  kohli    a
2    0.0    0.0   78.0  200
3  100.0  100.0   12.0  300

In [39]:
df.drop("dhoni",axis=1)

   dhruv  kohli    a
0  100.0  100.0  200
1  200.0   90.0  100
2    0.0   78.0  200
3  100.0   12.0  300

In [42]:
df.drop_duplicates() 
# no duplicates values

   dhruv  dhoni  kohli    a
0  100.0  100.0  100.0  200
1  200.0  100.0   90.0  100
2    0.0    0.0   78.0  200
3  100.0  100.0   12.0  300

In [43]:
data={"name":["a","b","a"],"marks":[100,20,100]}
df=pd.DataFrame(data)
df

  name  marks
0    a    100
1    b     20
2    a    100

In [44]:
df.drop_duplicates(keep="last")
# by default keep="first"

  name  marks
1    b     20
2    a    100

In [45]:
df.sort_values(by="marks")

  name  marks
1    b     20
0    a    100
2    a    100